name: mobile_assessment
description: Irecharge mobile team assessment

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts:
  json_annotation: ^4.8.1
  iconly: ^1.0.1
  lottie: ^2.3.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_animate: ^4.3.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  json_serializable: any
  build_runner: ^2.4.10

#flutter_icons:
#  ios: true
#  android: true
#  image_path_ios: 'assets/images/logo_transparent.png'
#  image_path_android: 'assets/images/logo_transparent.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/svg/
    # - assets/images/
    - assets/lottie/
  # assets:
  #   - assets/responses/
